name: Build Electron

on:
  workflow_dispatch:

  push:
    branches-ignore:
      - main
      - master

jobs:
  build-electron:
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Rebuild native dependencies
        run: npx electron-builder install-app-deps

      - name: Build app
        run: npm run build

      - name: Package Electron app
        run: npm run dist -- --publish=never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
          retention-days: 7